site_name: Material for MkDocs Style Guide
copyright: Copyright &copy; 2015-2022 <strong><a href="https://dyalog.com" target="_blank" rel="noopener">Dyalog, LTD</a></strong>
theme:
  name: material
  favicon: 'img/favicon-32.png'
  language: en
  logo: 'img/dyalog-white.svg'
plugins:
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: false
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown_tables_extended
  - toc:
      title: On this page
extra_css:
  - styles/custom-admonitions.css
  - styles/main.css
nav:
  - Home: index.md
  - Rules for Writing Documentation: rules.md
  - Style Guide: style.md
  - Images: images.md
  - Tables: tables.md
  - CSS: css.md
  - Process: process.md